# Generated by Django 3.1.1 on 2020-09-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfLink', models.TextField()),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('thumbnail', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
